import React,{useEffect,useRef,useState}from"react";import{Alert,Platform,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from"react-native";import*as Location from"expo-location";import*as TaskManager from"expo-task-manager";import*as SecureStore from"expo-secure-store";import{createClient}from"@supabase/supabase-js";import MapView,{Marker}from"react-native-maps";
const URL="https://qiwfbgswukaixyhlzekw.supabase.co",KEY="sb_publishable_bAIMCv0YQnAsWv_ppNzWhQ_uSRRFyTC",TASK="location-tracker-background-location";
const sb=createClient(URL,KEY);
TaskManager.defineTask(TASK,async({data,error})=>{if(error||!data?.locations?.length)return;const token=await SecureStore.getItemAsync("lt_token");if(!token)return;const l=data.locations[data.locations.length-1];await sb.rpc("save_my_location",{p_token:token,p_lat:l.coords.latitude,p_lng:l.coords.longitude,p_accuracy:l.coords.accuracy??null});});
async function start(){const f=await Location.requestForegroundPermissionsAsync();if(f.status!=="granted")throw Error("Location permission is required.");const b=await Location.requestBackgroundPermissionsAsync();if(b.status!=="granted")throw Error(Platform.OS==="ios"?"Allow Always location in Settings.":"Allow background location.");if(await Location.hasStartedLocationUpdatesAsync(TASK))return;const o={accuracy:Location.Accuracy.High,distanceInterval:0,timeInterval:5000,pausesUpdatesAutomatically:false};if(Platform.OS==="android")o.foregroundService={notificationTitle:"Location Tracker",notificationBody:"Your location is being shared every 5 seconds."};await Location.startLocationUpdatesAsync(TASK,o)}
async function stop(){if(await Location.hasStartedLocationUpdatesAsync(TASK))await Location.stopLocationUpdatesAsync(TASK)}
export default function App(){const[token,setToken]=useState(null),[u,setU]=useState(""),[lu,setLU]=useState(""),[pw,setPW]=useState(""),[sharing,setSharing]=useState(false),[err,setErr]=useState(""),[friends,setFriends]=useState([]),map=useRef(null);
useEffect(()=>{(async()=>{setToken(await SecureStore.getItemAsync("lt_token"));setU(await SecureStore.getItemAsync("lt_user")||"")})()},[]);
useEffect(()=>{if(!token)return;refresh();const i=setInterval(refresh,10000);return()=>clearInterval(i)},[token]);
async function refresh(){const a=await sb.rpc("my_location_status",{p_token:token});if(!a.error)setSharing(!!a.data?.sharing);const f=await sb.rpc("list_friends",{p_token:token});if(!f.error){const seen=new Set;setFriends((f.data||[]).filter(x=>{const k=String(x.id);if(seen.has(k))return false;seen.add(k);return true}))}}
async function login(){setErr("");const r=await sb.rpc("login_account",{p_username:lu.trim(),p_password:pw});if(r.error)return setErr(r.error.message);await SecureStore.setItemAsync("lt_token",r.data.token);await SecureStore.setItemAsync("lt_user",r.data.username);setToken(r.data.token);setU(r.data.username)}
async function share(){try{setErr("");await start();setSharing(true);await refresh()}catch(e){setErr(e.message)}}
async function unshare(){try{await stop();await sb.rpc("stop_my_location",{p_token:token});setSharing(false)}catch(e){setErr(e.message)}}
if(!token)return <SafeAreaView style={s.auth}><Text style={s.title}>Location Tracker</Text><TextInput style={s.input} placeholder="Username" value={lu} onChangeText={setLU}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={pw} onChangeText={setPW}/>{err?<Text style={s.err}>{err}</Text>:null}<Btn t="Log in" f={login}/></SafeAreaView>;
return <SafeAreaView style={s.safe}><Text style={s.title}>Location Tracker</Text><Text style={s.muted}>Signed in as {u}</Text><MapView ref={map} style={s.map} initialRegion={{latitude:39,longitude:-104.8,latitudeDelta:8,longitudeDelta:8}} showsUserLocation>{friends.map(x=>x.latitude!=null&&<Marker key={String(x.id)} coordinate={{latitude:+x.latitude,longitude:+x.longitude}} title={x.username} description={x.sharing?"Sharing location":"Last known location"}/>)}</MapView><View style={s.panel}><Text style={s.status}>{sharing?"🟢 Sharing location every 5 seconds":"⚪ Not sharing"}</Text>{sharing?<Btn t="Stop sharing" f={unshare}/>:<Btn t="Start sharing every 5 seconds" f={share}/>}<Text style={s.muted}>The app asks iOS/Android to deliver background GPS updates about every 5 seconds. The operating system can delay updates to save battery.</Text>{err?<Text style={s.err}>{err}</Text>:null}</View></SafeAreaView>}
function Btn({t,f}){return <TouchableOpacity style={s.btn} onPress={f}><Text style={s.bt}>{t}</Text></TouchableOpacity>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f3f4f6"},auth:{flex:1,justifyContent:"center",padding:24,backgroundColor:"#f3f4f6"},title:{fontSize:26,fontWeight:"800",padding:16},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:14,margin:8},btn:{backgroundColor:"#111827",padding:15,borderRadius:12,marginVertical:8,alignItems:"center"},bt:{color:"#fff",fontWeight:"800"},map:{flex:1},panel:{backgroundColor:"#fff",padding:16},status:{fontWeight:"800",marginBottom:4},muted:{color:"#6b7280",padding:8},err:{color:"#b91c1c",padding:8}});